# Generated by Django 4.2.2 on 2023-06-07 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Taks",
            new_name="Task",
        ),
    ]
